# Generated by Django 6.0.1 on 2026-01-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
