# Generated by Django 6.0.1 on 2026-01-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='qauntidade',
            new_name='quantidade',
        ),
    ]
