# Generated by Django 6.0.1 on 2026-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fornecedor',
            table='fornecedores',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produtos',
        ),
    ]
