# Generated by Django 6.0.1 on 2026-01-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_qauntidade_produto_quantidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('codigo', 'lote', 'vencimento', 'Fornecedor')},
        ),
    ]
