# Generated by Django 6.0.1 on 2026-01-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_fornecedor_table_alter_produto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
