# Generated by Django 6.0.1 on 2026-01-15 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_adicinar_produto', models.BooleanField(default=False)),
                ('pode_atualizar_produto', models.BooleanField(default=False)),
                ('pode_excluir_produto', models.BooleanField(default=False)),
                ('pode_adicinar_fornecerdor', models.BooleanField(default=False)),
                ('pode_atualizar_fornecerdor', models.BooleanField(default=False)),
                ('pode_excluir_fornecedor', models.BooleanField(default=False)),
                ('acesso_relatorios', models.BooleanField(default=False)),
                ('acesso_configuracao_sistema', models.BooleanField(default=False)),
                ('permissao_total', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configutacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_login', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expiracao', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
