# Generated by Django 6.0.1 on 2026-01-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracao',
            table='configuracao',
        ),
        migrations.AlterModelTable(
            name='login',
            table='login',
        ),
        migrations.AlterModelTable(
            name='recuperacao',
            table='recuperacao',
        ),
    ]
