# Generated by Django 6.0.1 on 2026-01-21 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracao',
            old_name='pode_adicionar_fornecerdor',
            new_name='pode_adicionar_fornecedor',
        ),
        migrations.RenameField(
            model_name='configuracao',
            old_name='pode_atualizar_fornecerdor',
            new_name='pode_atualizar_fornecedor',
        ),
        migrations.RenameField(
            model_name='configuracao',
            old_name='pode_excluir_fornecerdor',
            new_name='pode_excluir_fornecedor',
        ),
    ]
