# Generated by Django 6.0.1 on 2026-01-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_pode_adicionar_fornecerdor_configuracao_pode_adicionar_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recuperacao',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
