# Generated by Django 6.0.1 on 2026-01-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(choices=[('usuarios', 'Usuários'), ('produtos', 'Produtos'), ('fornecedor', 'Fornecedor')], max_length=20)),
                ('data_gerecao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'relatorios',
            },
        ),
    ]
