# Generated by Django 6.0.1 on 2026-01-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relatorio',
            table='relatorio',
        ),
    ]
